# Generated by Django 4.1.2 on 2022-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=6)),
                ('flat_owner', models.CharField(max_length=100)),
            ],
        ),
    ]
