# Generated by Django 4.1.2 on 2022-11-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_proj', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flat',
        ),
    ]
